on:
  push:
    branches:
      - main
      - master

jobs:
  ubuntu_hello:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello World from Ubuntu Runner!!"
      - run: echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event"
      - run: echo "ğŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "GitHub Repository URL is ${{ github.repositoryUrl}} and branch is ${{ github.ref_name }} "
      - name: Cloning GitHub Repo 
        uses: actions/checkout@v3
      - name: List files in workspace
        run: ls ${{ github.workspace }}
      - name: Present Working Directory
        run: pwd;ls
